CREATE TABLE IF NOT EXISTS USER (
    USER_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    USERNAME VARCHAR(128) NOT NULL UNIQUE,
    PASSWORD VARCHAR(256) NOT NULL
);

CREATE TABLE IF NOT EXISTS AUTH_USER_GROUP (
    AUTH_USER_GROUP_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    USERNAME VARCHAR(128) NOT NULL,
    AUTH_GROUP VARCHAR(128) NOT NULL,
    CONSTRAINT USER_AUTH_USER_GROUP_FK FOREIGN KEY(USERNAME) REFERENCES USER(USERNAME),
    UNIQUE (USERNAME, AUTH_GROUP)
);

CREATE TABLE IF NOT EXISTS CITY (
     ID BIGINT PRIMARY KEY,
     NAME VARCHAR(128) NOT NULL,
     COUNTRY VARCHAR(128) NOT NULL,
     LONGITUDE DECIMAL NOT NULL,
     LATITUDE DECIMAL NOT NULL,
     MAIN VARCHAR(128) NOT NULL,
     TEMPERATURE DECIMAL NOT NULL,
     HUMIDITY DECIMAL NOT NULL,
     WINDSPEED DECIMAL NOT NULL
)