### Get weather in city with specific id
GET http://localhost:8080/api/weather?id=
Accept: application/json

### Get closest city in database to given location
GET http://localhost:8080/api/v1/closestcity?latitude=44.4268&longitude=26.1025
Accept: */*
Cache-Control: no-cache

### Get all cities in the database
GET http://localhost:8080/api/v1/cities
Accept: */*
Cache-Control: no-cache