### Fill in with desired id
GET http://localhost:8080/api/weather?id=
Accept: application/json

### Example
#POST http://localhost:8080/api/
#Content-Type: application/json
#
#{
#  "text": "Im so happy."
#}
